---
version: '2.4'
services:
  mongodb:
    image: mongo:4.2.1
    container_name: mongod
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb

  parity:
    image: parity/parity:v2.7.2-stable
    container_name: parity
    command: --config /app/parity_config.toml
    working_dir: /app
    user: root
    restart: unless-stopped
    ports:
      - '127.0.0.1:8545:8545/tcp'
      - '30303:30303/tcp'
      - '30303:30303/udp'
    volumes:
      - ./chain.json:/app/chain.json
      - ./parity_config.toml:/app/parity_config.toml
      - ./chains:/app/chains

  ethstats-client:
    image: quay.io/ambrosus/ethstats-client
    container_name: ethstats_client
    restart: unless-stopped
    logging:
      options:
        max-size: '100m'
        max-file: '3'
    depends_on:
      - parity
    environment:
      RPC_HOST: parity
      WS_SERVER: wss://stats-api.<ENTER_DOMAIN_HERE>
      WS_SECRET: Z2hTiWBUfTNc5o9BAm
      INSTANCE_NAME: 'atlas <ENTER_YOUR_ADDRESS_HERE>'

  worker: &atlas-props
    image: ambrosus/ambrosus-node:<ENTER_DOCKER_TAG_HERE>
    container_name: atlas_worker
    command: sh -c 'yarn migrate && yarn start:atlas'
    restart: unless-stopped
    logging:
      options:
        max-size: '100m'
        max-file: '3'
    depends_on:
      - mongodb
      - parity
    environment:
      - WEB3_NODEPRIVATEKEY=<ENTER_YOUR_PRIVATE_KEY_HERE>
      - HEAD_CONTRACT_ADDRESS=<ENTER_YOUR_HEAD_CONTRACT_ADDRESS_HERE>
      - WEB3_RPC=http://parity:8545
      - MONGO_HOSTS=mongodb:27017
      - MONGO_DB_NAME=ambrosus
      - AUTHORIZATION_WITH_SECRET_KEY_ENABLED=false
      - NODE_ENV=production

  server:
    container_name: atlas_server
    <<: *atlas-props
    command: sh -c 'yarn start:server'
    logging:
      options:
        max-size: '100m'
        max-file: '3'
    depends_on:
      - worker
    ports:
      - 80:9876
